services:
  frontend:
    build: ./frontend/frontend-react
    container_name: gymtracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - gymtracker-network

  backend:
    build: ./backend
    container_name: gymtracker-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      CORS_ALLOWED-ORIGINS: ${CORS_ALLOWED_ORIGINS}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - gymtracker-network

  db:
    image: postgres:18.1-alpine
    container_name: gymtracker-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gymtracker-network

networks:
  gymtracker-network:
    driver: bridge

volumes:
  db-data: