services:
  - type: web
    name: gymtracker-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: gymtracker-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gymtracker-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: gymtracker-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: gymtracker-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: gymtracker-db
          property: password
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: gymtracker-frontend
          property: host

  - type: web
    name: gymtracker-frontend
    runtime: static
    rootDir: ./frontend/frontend-react
    buildCommand: VITE_API_URL=https://$VITE_API_URL npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: gymtracker-backend
          property: host

databases:
  - name: gymtracker-db
    plan: free
    databaseName: gymtracker_db